(* Automatically generated file, do not change *)
theory All_of_Termination_and_Complexity
  imports
    AC_Dependency_Pairs
    AC_Dependency_Pairs_Impl
    AC_Reduction_Pair_Processor
    AC_Reduction_Pair_Processor_Impl
    AC_Subterm_Criterion
    AC_Subterm_Criterion_Impl
    Argument_Filter_Impl
    Bounded_Increase
    Bounded_Increase_Impl
    Complex_Constant_Removal
    Complex_Constant_Removal_Impl
    Complexity_Framework
    Complexity_Framework_Impl
    Complexity_Impl
    Countable_Term
    DP_Transformation_Impl
    DT_Transformation
    DT_Transformation_Impl
    Defaults
    Dependency_Graph
    Dependency_Graph_Impl
    Flat_Context_Closure
    Flat_Context_Closure_Impl
    Generalized_Usable_Rules
    Generalized_Usable_Rules_Impl
    Generic_Reduction_Pair_Processor
    Generic_Reduction_Pair_Processor_Impl
    Generic_Usable_Rules
    Generic_Usable_Rules_Impl
    Icap
    Icap_Impl
    Innermost_Usable_Rules
    Innermost_Usable_Rules_Impl
    Instantiation
    Instantiation_Impl
    Matchbounds
    Matchbounds_Impl
    Monadic_Rewriting
    Monadic_Rewriting_Impl
    Multi_Algebra
    Multi_Algebra_Impl
    Narrowing
    Narrowing_Impl
    Q_Reduction
    Q_Reduction_Impl
    Raise_Compatibility
    Raise_Compatibility_Impl
    Raise_Consistency
    Reduction_Pair_Proc_Impl
    Rewriting
    Rewriting_Impl
    Right_Ground_Termination
    Right_Ground_Termination_Impl
    Size_Change_Termination
    Size_Change_Termination_Processors
    Size_Change_Termination_Processors_Impl
    Split_Impl
    String_Reversal_Impl
    Subterm_Criterion
    Subterm_Criterion_Impl
    Tcap_Dpp_Impl
    Termination_Processors
    Uncurry
    Uncurry_Impl
    Usable_Replacement_Map
    Usable_Replacement_Map_Impl
    Usable_Rules
    Usable_Rules_Complexity
    Usable_Rules_Complexity_Impl
    Usable_Rules_Impl
    WDP_Transformation
    WDP_Transformation_Impl
begin
end
