(* Automatically generated file, do not change *)
theory All_of_Confluence_and_Completion
  imports
    Check_Joins
    Commutation
    Completion
    Critical_Pair_Closing_Systems
    Critical_Pair_Closure_Impl
    Critical_Pairs_Impl
    Decreasing_Diagrams2
    Development_Closed
    Development_Closed_Impl
    Equational_Reasoning
    Equational_Reasoning_Impl
    LS_Basics
    LS_Bounded_Duplicating
    LS_Common
    LS_Currying
    LS_Currying2
    LS_Extras
    LS_General
    LS_Left_Linear
    LS_Modularity
    LS_Persistence
    LS_Persistence_Impl
    LS_Prelude
    Non_Commutation_Impl
    Non_Confluence
    Non_Confluence_Impl
    Okui_Criterion
    Okui_subsumes_DC
    Ordered_Completion
    Ordered_Completion_Impl
    Ordered_Completion_More
    Orthogonality_Impl
    Parallel_Closed
    Parallel_Closed_Impl
    Parallel_Critical_Pairs
    Parallel_Critical_Pairs_Impl
    Redundant_Rules
    Redundant_Rules_Impl
    Rule_Labeling_Impl
    Strongly_Closed
    Strongly_Closed_Impl
    Usable_Rules_NJ
    Usable_Rules_NJ_Impl
    Usable_Rules_NJ_Unif
    Usable_Rules_NJ_Unif_Impl
begin
end
