#!/usr/bin/env bash
#
# Author: Christian Sternagel
#
# DESCRIPTION: build and copy heap images

REMOTE_BUILD=$ISAFOR_BASE/lib/remote_build.jar

if [ -e $REMOTE_BUILD ]
then
  $ISABELLE_TOOL scala $REMOTE_BUILD "$@"
else
  echo -e "missing file \"$ISAFOR_BASE/lib/remote_build.jar\""
  echo -e "run \"make remote_build\" in \"$ISAFOR_BASE\" to generate it"
  exit 1
fi
