(* Automatically generated file, do not change *)
theory All_of_Orderings
  imports
    AC_Aux
    AC_Weight
    Ackbo
    Ackbo_Impl
    Ackbo_more
    Ackbo_wf
    Argument_Filter
    Branch_and_Bound
    CoWPO
    CoWPO_Impl
    Complexity
    Dual_Multiset
    Dual_Multiset_Impl
    Embedding_Trs
    F_Algebra
    Formula
    GWPO_Impl
    IA_Checker
    Integer_Arithmetic
    Jordan_Normal_Form_Complexity_Approximation
    KBO_Impl
    KBO_More
    LPO_More
    Lexicographic_Extension_More
    Lexicographic_Orders
    Linear_Poly_Complexity
    Linear_Poly_Interpretation
    Linear_Poly_Order
    Linear_Polynomial
    List_Order_Implementations
    Matrix_Base
    Matrix_Poly
    Matrix_TRS
    Matrix_TRS_Impl
    Max_Monus
    Max_Monus_Impl
    Max_Polynomial
    Max_Polynomial_Aux
    Max_Polynomial_Impl
    Min_Set_Order
    Min_Set_Order_Impl
    Monotone_Algebra
    Multiset_Extension_More
    Non_Inf_Order
    Non_Inf_Order_Impl
    Non_Inf_Orders
    Ordered_Algebra
    Ordered_Algebra_Impl
    Ordered_Rewriting
    Ordered_Rewriting_Impl
    Poly_Order
    Poly_Order_Neg
    Quasi_Order
    RPO_Impl
    RPO_More
    Reduction_Order
    Reduction_Order_Impl
    Reduction_Pair
    Reduction_Pair_Implementations
    SCNP
    SCNP_Impl
    SPO
    SPO_Impl
    Set_Order
    Set_Order_Impl
    Show_Literal_Polynomial
    Simple_Termination
    Sorted_Algebra
    Status_Impl
    Subterm_Multiset
    Term_Order
    Term_Order_Extension
    Term_Order_Impl
    WPO_Impl
begin
end
