#!/bin/sh


afppath=hg@bitbucket.org/isa-afp/afp-devel

function help() {
  echo "Script for managing a local copy of the AFP"
  echo -e "\nlist of commands:\n"
  echo " hg       forward a hg command to the remote AFP repo"
  echo " build    build the heap image HOL-AFP"
}

function hgcmd() {
  ssh colo2-c703.uibk.ac.at "cd /mercurial/afp && hg $@"
}

case $1 in
  hg)
    shift 1
    case $1 in
      push)
        hgcmd $1 ssh://${afppath}
      ;;
      pull|out|"in")
        hgcmd $1 http://${afppath}
      ;;
      update|commit|merge)
        hgcmd $@
      ;;
      fetch)
        echo "command '$1' not allowed; use 'pull', 'merge', 'commit'"
        echo "cycle instead (avoids interference with 'incoming' hook)"
        exit 1
      ;;
      *)
        echo "command '$@' not allowed"
        exit 1
    esac
  ;;
  build)
    isadev build -d . -b HOL-AFP;;
  help)
    help;;
  *)
    echo -e "I don't know what to do!\nTry '$0 help'" > /dev/stderr;;
esac
